export enum actionsTypes {
  GET_DATA_LIST = 'GET_DATA_LIST',
  SET_DATA_LIST = 'SET_DATA_LIST',
  TOGGLE_LOADING = 'TOGGLE_LOADING',
  SENT_NEW_DATA = 'SENT_NEW_DATA',
  DELETE_DATA = 'DELETE_DATA',
  SELECT_DATA_TO_EDIT = 'SELECT_DATA_TO_EDIT',
  RESET_STATE = 'RESET_STATE',
}
